# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  Macos:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: port install gcc g++ python3-pip libbz2-dev ccache zlib1g-dev uuid-dev
    - run: PATH=$PATH:$HOME/bin
    - run: npm i
    - run: npm i -g typescript
    - run: tsc
    - run: npm run test
  
  Ubuntu-20:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt install gcc g++ python3-pip libbz2-dev ccache zlib1g-dev uuid-dev
    - run: PATH=$PATH:$HOME/bin
    - run: npm i
    - run: npm i -g typescript
    - run: tsc
    - run: npm run test

  Xenial:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt install gcc-4.9 g++-4.9 python3-pip libbz2-dev ccache zlib1g-dev uuid-dev
    - run: PATH=$PATH:$HOME/bin
    - run: npm i
    - run: npm i -g typescript
    - run: tsc
    - run: npm run test
    
    
